from enum import Enum


class FactCategory(str, Enum):
    ASTRONOMY = "astronomy"
    HISTORY = "history"
    BIOLOGY = "biologiy"
    TECHNOLOGY = "technology"
    NATURE = "nature"
    MISCONCEPTION = "misconception"
    OBSCURE = "obscure"
    GEOGRAPHY = "geography"
    PHYSICS = "physics"
    CHEMISTRY = "chemistry"
    ENGINEERING = "engineering"
    LAW = "law"
    CRIME = "crime"
    PSYCHOLOGY = "psychology"
    SPORTS = "sports"
    ART = "art"
    MEDICINE = "medicine"
    LITERATURE = "literature"
    MOVIES = "movies"
    MYTHOLOGY = "mythology"
    MATHEMATICS = "mathematics"
    FOOD = "food"
    OCEAN = "ocean"
    LANGUAGES = "languages"
    MUSIC = "music"
    RELIGION = "religion"
    MILITARY = "military"
    CULTURE = "culture"
    FASHION = "fashion"
